using System.Text;
using System.Text.Json;
using QAOrchestrator.Domain;

namespace QAOrchestrator.Generation;

public sealed class TestCandidateWriter
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        WriteIndented = true
    };

    public BoostCandidate Write(TargetSolution solution, BoostCandidate candidate)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(candidate.Location.CandidatePath)!);
        File.WriteAllText(candidate.Location.CandidatePath, BuildCandidateContent(solution, candidate));
        File.WriteAllText(candidate.Location.CandidatePath + ".metadata.json", JsonSerializer.Serialize(ToMetadata(candidate), JsonOptions));
        return candidate with { Status = CandidateStatus.Generated };
    }

    public BoostCandidate MoveToStatus(BoostCandidate candidate, CandidateStatus status, string? failureReason = null)
    {
        var statusFolder = status == CandidateStatus.Accepted ? "accepted" : "failed";
        var newPath = TestLocationResolver.MoveCandidatePathToStatus(candidate.Location.CandidatePath, "pending", statusFolder);
        Directory.CreateDirectory(Path.GetDirectoryName(newPath)!);

        if (File.Exists(candidate.Location.CandidatePath))
        {
            File.Move(candidate.Location.CandidatePath, newPath, overwrite: true);
        }

        if (File.Exists(candidate.Location.CandidatePath + ".metadata.json"))
        {
            File.Move(candidate.Location.CandidatePath + ".metadata.json", newPath + ".metadata.json", overwrite: true);
        }

        var newLocation = candidate.Location with { CandidatePath = newPath };
        var updated = candidate with { Location = newLocation, Status = status, FailureReason = failureReason };
        File.WriteAllText(newPath + ".metadata.json", JsonSerializer.Serialize(ToMetadata(updated), JsonOptions));
        return updated;
    }

    private static object ToMetadata(BoostCandidate candidate)
        => new
        {
            sourceFile = candidate.SourceClass.FilePath,
            sourceClass = candidate.SourceClass.ClassName,
            sourceMethods = candidate.SourceClass.PublicMethods,
            existingExactTests = candidate.Location.ExistingExactTestFiles,
            existingSimilarTests = candidate.Location.ExistingSimilarTestFiles,
            candidatePath = candidate.Location.CandidatePath,
            suggestedFinalPath = candidate.Location.SuggestedFinalPath,
            testType = candidate.Location.TestType.ToString(),
            reason = candidate.Reason,
            confidence = candidate.Location.Confidence,
            status = candidate.Status.ToString(),
            failureReason = candidate.FailureReason
        };

    private static string BuildCandidateContent(TargetSolution solution, BoostCandidate candidate)
    {
        var testProject = FindTestProject(solution, candidate.Location.MatchingTestProject);
        var assertion = testProject?.AssertionFramework ?? AssertionFramework.Unknown;
        var mock = testProject?.MockFramework ?? MockFramework.Unknown;
        var testFramework = testProject?.TestFramework ?? TestFramework.XUnit;
        var ns = BuildNamespace(testProject, candidate);
        var methodName = BuildMethodName(candidate);

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated>");
        builder.AppendLine("// QA Orchestrator safe candidate. Review before moving to the suggested final location.");
        builder.AppendLine("// </auto-generated>");
        builder.AppendLine("using System;");
        if (testFramework == TestFramework.XUnit)
        {
            builder.AppendLine("using Xunit;");
        }

        if (assertion == AssertionFramework.AwesomeAssertions)
        {
            builder.AppendLine("using AwesomeAssertions;");
        }
        else if (assertion == AssertionFramework.FluentAssertions)
        {
            builder.AppendLine("using FluentAssertions;");
        }

        if (mock == MockFramework.Moq)
        {
            builder.AppendLine("using Moq;");
        }

        builder.AppendLine();
        builder.AppendLine($"namespace {ns};");
        builder.AppendLine();
        builder.AppendLine($"public sealed class {Path.GetFileNameWithoutExtension(candidate.CandidateName)}");
        builder.AppendLine("{");
        builder.AppendLine("    [Fact(Skip = \"QA Orchestrator generated a safe candidate skeleton. Review metadata before enabling.\")]");
        builder.AppendLine($"    public void {methodName}()");
        builder.AppendLine("    {");
        builder.AppendLine("        // Arrange");
        builder.AppendLine($"        // Source: {candidate.SourceClass.RelativePath.Replace('\\', '/')}");
        builder.AppendLine($"        // Suggested final location: {candidate.Location.SuggestedFinalPath}");
        builder.AppendLine();
        builder.AppendLine("        // Act");
        builder.AppendLine("        // Add the project-specific invocation here after reviewing existing patterns.");
        builder.AppendLine();
        builder.AppendLine("        // Assert");
        builder.AppendLine("        // Keep this candidate isolated until it compiles and adds coverage.");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string BuildMethodName(BoostCandidate candidate)
    {
        if (candidate.SourceClass.Kind == TestableSourceKind.Endpoint)
        {
            return "Should_ReturnExpectedResult_When_RequestIsValid";
        }

        if (candidate.ExistingTestMatch.HasExactOrStrongMatch)
        {
            return "Should_CoverAdditionalScenario_When_ExistingTestsDoNot";
        }

        return "Should_CoverBehavior_When_RequestIsValid";
    }

    private static string BuildNamespace(TargetProject? testProject, BoostCandidate candidate)
    {
        var baseNamespace = testProject?.Name.Replace("-", ".", StringComparison.Ordinal) ?? "QAOrchestrator.GeneratedCandidates";
        var sourceNamespace = candidate.SourceClass.Namespace;
        if (string.IsNullOrWhiteSpace(sourceNamespace))
        {
            return baseNamespace;
        }

        var tail = sourceNamespace.Split('.').TakeLast(Math.Min(3, sourceNamespace.Split('.').Length));
        return baseNamespace + "." + string.Join(".", tail);
    }

    private static TargetProject? FindTestProject(TargetSolution solution, string? projectName)
        => projectName is null
            ? solution.Projects.FirstOrDefault(project => project.IsTestProject)
            : solution.Projects.FirstOrDefault(project => project.IsTestProject && project.Name.Equals(projectName, StringComparison.OrdinalIgnoreCase));
}
